export { default as Logo } from "./bird.jpg"
export { default as Facebook } from "./facebook.png"
export { default as Instagram } from "./instagram.png"
export { default as Vkontakte } from "./vk.png"
export { default as Background } from "./background.png"
export { default as Temperature } from "./temperature.png"
